name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.DEVOPS_PEM }}
          port: 22
          script: |
            echo "✅ SSH access confirmed"

            # Update and install Docker if missing, non-interactive
            if ! command -v docker &> /dev/null; then
              sudo apt-get update -qq
              sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            # Install Docker Compose v2 if missing
            if ! docker compose version &> /dev/null; then
              DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
              mkdir -p $DOCKER_CONFIG/cli-plugins
              curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
              chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
            fi

            # Remove old project folder
            rm -rf ~/e-comarce

            # Clone latest code
            git clone https://github.com/SHIVANGOUDAPATIL1234/e-comarce.git ~/e-comarce
            cd ~/e-comarce

            # Pull latest Docker image (with sudo)
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/e-comarce:latest

            # Restart container using docker compose (with sudo)
            sudo docker compose down -v || true
            sudo docker compose up -d
