name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "✅ SSH access confirmed"

            # Kill any apt process to avoid lock
            sudo killall apt apt-get || true
            sudo rm -f /var/lib/dpkg/lock-frontend
            sudo rm -f /var/cache/apt/archives/lock

            # Install Docker
            if ! command -v docker &> /dev/null; then
              echo "⚙️ Installing Docker..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker $USER
            fi

            # Install Docker Compose v2
            if ! docker compose version &> /dev/null; then
              echo "⚙️ Installing Docker Compose V2..."
              DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
              mkdir -p $DOCKER_CONFIG/cli-plugins
              curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
              chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
            fi

            # Refresh Docker group and deploy
            newgrp docker <<EONG
              rm -rf ~/e-comarce
              git clone https://github.com/SHIVANGOUDAPATIL1234/e-comarce.git ~/e-comarce
              cd ~/e-comarce

              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/e-comarce:latest

              docker compose down -v || true
              docker compose up -d
            EONG
